### ISSUE TITLE
Numbering of .md files

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro-old#15]
@ArtemSokolov histoCAT feature extraction will be performed before the cell type calling. Should I rename the files from 03->04?

**Comment by ArtemSokolov** [comment]
I folded HistoCAT feature extraction under `02-segment.md`: https://github.com/labsyspharm/mcmicro/blob/master/02-segment.md#quantification-of-segmentation-masks-using-headless-histocat-quantify

The high-level organization is:

1. Stitching and Registration
2. Segmentation, which is broken down into
  a. Probability mask generation (UNet method)
  b. Binarization of masks (S3segmenter)
  c. Quantification (HistoCAT)
3. Downstream analysis, which is broken down into
  a. Clustering and per-cluster cell type assignment
  b. Per-cell assignment of cell type identity using prior knowledge

I'm open to other organizational schemes.

**Comment by DenisSch** [comment]
We will most likely introduce multiple segmentations, so I would prefer to keep them separated. Could we have 4 steps? 3 step being feature extraction and quantification?

**Comment by ArtemSokolov** [comment]
Sure. I'm fine with it.

**Comment by DenisSch** [comment]
Do you want me to adapt it or are you going to do it? I can add another .md file and reference it accordingly.

**Comment by ArtemSokolov** [comment]
I would say that the initial goal is just to get the content in there. Any form you want to share it in should be fine.
