### ISSUE TITLE
Difficulty Highlighting Bash Text

### ISSUE THREAD

**Issue by bioinfonerd** [labsyspharm/mcmicro-old#22]
Commands listed in the instructions are difficult to highlight.  

Guessing something with bookdown rendering as regular text there is no difficulty.

**Comment by ArtemSokolov** [comment]
We have a highlight.js module that @jmuhlich put together specifically for bash: https://github.com/labsyspharm/mcmicro/tree/master/doc/build/libs/ext

You need to source it with an HTML header. See https://github.com/labsyspharm/rnaseq/blob/master/02-data.md for an example.

Here's what the final render looks like: https://labsyspharm.github.io/rnaseq/data.html

**Comment by bioinfonerd** [comment]
Thank you this helps
