### ISSUE TITLE
Git Submodule doesn't handle git lfs correctly

### ISSUE THREAD

**Issue by bioinfonerd** [labsyspharm/mcmicro-old#23]
Need to further research how to pull this automatically or build a bridge

- allow for automatic updating the pipeline with new developer content
- some github repos utilize git lfs, but git submodule doesn't handle it correctly
- git lfs clone solves it, but git submodule update should do it automatically

**Comment by bioinfonerd** [comment]
This is to remind me to look into this eventually

**Comment by ArtemSokolov** [comment]
All data and model storage will be on S3 going forward.
